# Linear Algebra review

In [1]:
import numpy as np

## Defining matrices and vectors


In [6]:
# Every row is a list. Rows are separeted with commas inside another list.
matrix = np.array([[1,2,3], 
                   [1,1,2], 
                   [0,1,2]])
print(matrix)

[[1 2 3]
 [1 1 2]
 [0 1 2]]


In [8]:
# A row vector is a list containing only one list with several elements
rowVec = np.array([[1, 2, 3, 4]])
print(rowVec)

[[1 2 3 4]]


In [12]:
# A column vector is a list containing several lists with a single element
colVec = np.array([[1],
                   [2],
                   [3],
                   [4]])
print(colVec)

[[1]
 [2]
 [3]
 [4]]


## Transpose

In [13]:
# Use attribute .T

print(matrix.T)
print(rowVec.T)
print(colVec.T)

[[1 1 0]
 [2 1 1]
 [3 2 2]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


## Arithmetic operations

Arithmetic operations like +, -, /, * and ** are performed elementwise

<p align="justify">
Special operations:
<ul>
    <li>Matrix multiplication: matrix1 @ matrix2, assuming it is well defined</li>
    <li>Dot product: use .dot() method. For example, dot product between u and v, do v.dot(u). If u and v are both col or row vec, one has to be transposed before calling the method</li>
    <li>Cross product: use np.cross(v1,v2) and make sure the vectors are rows</li>

</ul>
</p>

In [16]:
print(matrix + matrix.T)

[[2 3 3]
 [3 2 3]
 [3 3 4]]


In [17]:
# Elementwise product

print(matrix*matrix.T)

[[1 2 0]
 [2 1 2]
 [0 2 4]]


In [22]:
B = np.array([[1,1],
              [0,1],
              [2,2]])
# Matrix multiplication
print(B @ B.T)
print(B.T @ B)

[[2 1 4]
 [1 1 2]
 [4 2 8]]
[[5 5]
 [5 6]]


## Determinat

In [26]:
print(np.linalg.det(matrix))

-1.0


## Trace

In [27]:
print(np.trace(matrix))

4


## Inverse

In [28]:
print(np.linalg.inv(matrix))

[[ 0.  1. -1.]
 [ 2. -2. -1.]
 [-1.  1.  1.]]


## Ejemplo 1: dada una matriz A, calcular A'A, su determinante y su traza. Reptir para AA'

In [33]:
A = np.array([[1,1],
              [0,1],
              [2,2]])

res1 = A.T @ A
det1 = np.linalg.det(res1)
tra1 = np.trace(res1)
print('Resultados de A\'A: \nProducto: \n', res1, '\nDeterminante: ', det1, '\nTraza: ', tra1)


res2 = A @ A.T
det2 = np.linalg.det(res2)
tra2 = np.trace(res2)
print('Resultados de AA\': \nProducto: \n', res2, '\nDeterminante: ', det2, '\nTraza: ', tra2)

Resultados de A'A: 
Producto: 
 [[5 5]
 [5 6]] 
Determinante:  4.999999999999999 
Traza:  11
Resultados de AA': 
Producto: 
 [[2 1 4]
 [1 1 2]
 [4 2 8]] 
Determinante:  0.0 
Traza:  11


## Ejemplo 2: Hallar la inversa de una matriz

In [35]:
Mat = np.array([[1,2,3],
              [1,1,2],
              [0,1,2]])
inv = np.linalg.inv(Mat)
print(inv)

[[ 0.  1. -1.]
 [ 2. -2. -1.]
 [-1.  1.  1.]]


## Eigenvalues and eigenvectors

In [48]:
eigVal, eigVec = np.linalg.eig(Mat)
print('Eigenvalues: \n', eigVal, '\nEigenvectors: \n', eigVec)

Eigenvalues: 
 [-0.37720285  0.72610945  3.65109341] 
Eigenvectors: 
 [[ 0.44287099  0.71390288  0.7763    ]
 [-0.82644005  0.5508072   0.53918151]
 [ 0.34765231 -0.43238189  0.32656027]]


## Ejemplo 3: Calcular los vectores y valores propios de una matriz

In [47]:
A = np.array([[2,1],
              [1,2]])
eigVal, eigVec = np.linalg.eig(A)
print('Eigenvalues: \n', eigVal, '\nEigenvectors: \n', eigVec)

Eigenvalues: 
 [3. 1.] 
Eigenvectors: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
